### PR TITLE
Various bugfixes

### PR DESCRIPTION
**Pull request by Luke-Nukem**

### CODE REVIEW

**Comment by Luke-Nukem** [comment]
Fixes issue #216, please close on merge.

**Comment by Luke-Nukem** [comment]
Also addresses issue #238

**Comment by Luke-Nukem** [comment]
Addresses issue #157

**Comment by Luke-Nukem** [comment]
Adresses issue #250

**Comment by sumnerfit** [comment]
Issue with dev cards being played (not an error, implementation issue).  The rule is you can't purchase and play a dev card in the same turn.  I purchased a dev card (received monopoly) but couldn't play a previously purchased card (in this case year of plenty).

image

**Comment by Luke-Nukem** [comment]
Hmm, that might need a more complex solution then.

**Pull request merged**
