### PR TITLE
Feature/largest army

### PR DESCRIPTION
**Pull request by sumnerfit**
To test:

Use {url:3000}/?setup=skip&startWithCards=20

Test player receives largest army at start of following turn, and can lose it to an opponent.
Test two players eligible on same turn, neither gets it.
Check scores update as army changes hands.

### CODE REVIEW

**Comment by timack** [comment]
Am getting a console error on this:

image

**Comment by timack** [comment]
Looks like that above issue related to my knight update - so will have a crack at fixing it.

**Comment by timack** [comment]
Somehow both my player got longest road -- with out building any roads?

image

**Comment by sumnerfit** [comment]
The longest road bug is in master.

**Comment by timack** [comment]
Looks merging now ... might look at doing something bit more elegant that the native alert notification if we have time.

**Pull request merged**
